# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '7.1'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/wayde191/IHakulaSpecs.git'

use_frameworks!

target 'IHakulaInfrastructureTesting' do
    pod 'IHakulaInfrastructure', :path => '/Users/CNwwsun/iHakula/IHakulaInfrastructure'
end

target 'IHakulaInfrastructureTestingTests' do

end

